name: Solo-Projects Standard Setups
description: configuration to enable make targets
inputs:
  GLOO_EE_GCR_KEY:
    required: true
    description: access key for Google Cloud
  QUAY_IO_PASSWORD:
    required: true
    description: access key for Quay Image repository
  GITHUB_TOKEN:
    required: true
    description: access token for use in CI
  
runs:
  using: "composite"
  steps:
    # save money by cancelling obsolete compute
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    # enable interaction with gcloud buckets
    - name: Setup - gcloud / gsutil
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ inputs.GLOO_EE_GCR_KEY }}'
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: gloo-ee
    # enable pushing built images to quay repo
    - name: Quay Login
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: solo-io+solobot
        password: ${{ inputs.QUAY_IO_PASSWORD }}
    # enable a few builder base images to be pulled
    - name: Gcloud Login
      shell: bash
      run: gcloud auth configure-docker
    # pre-load the go mod dependencies, and set up `go run` to function
    - name: Prep Go Runner
      uses: ./.github/workflows/composite-actions/prep-go-runner
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
