changelog:
  - type: NON_USER_FACING
    resolvesIssue: false
    issueLink: https://github.com/solo-io/solo-projects/issues/2430
    description: Implement single-cluster GetConfigDumps.
  - type: NON_USER_FACING
    resolvesIssue: false
    issueLink: https://github.com/solo-io/gloo/issues/4933
    description: Implement single-cluster GetConfigDumps.
