steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ci/id_rsa.enc
  - --plaintext-file=ci/id_rsa
  - --location=global
  - --keyring=build
  - --key=build-key

- name: 'soloio/dep'
  args: ['ensure']
  env: ['PROJECT_ROOT=github.com/solo-io/solo-kit']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'sqoop-linux-amd64', 'github.com/solo-io/solo-kit/projects/sqoop/cmd']
  env: ['PROJECT_ROOT=github.com/solo-io/solo-kit']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'sqoop-linux-amd64', 'github.com/solo-io/solo-kit/projects/hypergloo']
  env: ['PROJECT_ROOT=github.com/solo-io/solo-kit']

artifacts:
  objects:
    location: 'gs://artifacts.solo.io/'
    paths: ['sqoop-linux-amd64']
