steps:

# Setup SSH
# These are required before prepare-workspace
- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=ci/id_rsa.enc
    - --plaintext-file=/root/.ssh/id_rsa
    - --location=global
    - --keyring=build
    - --key=build-key
  id: "get-ssh-key"

- name: "gcr.io/cloud-builders/git"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      mv ./ci/github_known_hosts /root/.ssh/known_hosts
      git config --global url."ssh://git@github.com/solo-io".insteadOf https://github.com/solo-io
  id: "configure-git"

- name: "golang:1.18.2"
  args: ["go", "env", "-w", "GOPRIVATE=github.com/solo-io"]
  id: "set-private"

# clones Gloo so it can be setup & tested
# All steps after this must set working directory to use the cloned Gloo source

# $COMMIT_SHA is a default gcloud env var, to run via cloudbuild submit use:
# gcloud builds submit --substitutions COMMIT_SHA=<commitsha>,REPO_NAME=solo-io/solo-projects --project gloo-ee
- name: "gcr.io/solo-public/prepare-go-workspace:0.4.28"
  args:
    - "--repo-name"
    - "$REPO_NAME"
    - "--repo-sha"
    - "$COMMIT_SHA"
    - "--repo-output-dir"
    - "."
    - "--use-ssh"
  id: "prepare-workspace"

- name: gcr.io/cloud-builders/gsutil
  entrypoint: "bash"
  args:
    [
      "-c",
      'mkdir -p ./gopath/pkg && cd ./gopath/pkg && gsutil cat gs://$PROJECT_ID-cache/solo-projects/solo-projects-mod.tar.gz | tar -xzf - || echo "untar mod cache failed; continuing because we can download deps as we need them"',
    ]
  waitFor: ["-"]
  id: "untar-mod-cache"

# e2e-go-mod-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-go-mod-ginkgo
# Must set the GOPATH to tell the container the workspace has already been set up (by the prepare-workspace step above)
- name: node:16
  secretEnv: ["NPM_TOKEN"]
  dir: "/workspace/solo-projects/projects/ui"
  entrypoint: yarn
  args: ["install"]
  waitFor: ["prepare-workspace"]
  id: "yarn-install"

- name: "gcr.io/cloud-builders/yarn"
  secretEnv: ["NPM_TOKEN"]
  args: ["build"]
  dir: "/workspace/solo-projects/projects/ui"
  waitFor: ["yarn-install"]
  id: "yarn-build"

- name: node:16
  secretEnv: ["NPM_TOKEN"]
  dir: "/workspace/solo-projects/projects/gloo/pkg/plugins/graphql/v8go"
  entrypoint: yarn
  args: ["install"]
  waitFor: ["prepare-workspace"]
  id: "yarn-install-graphql-js"

- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args:
    [
      "-c",
      'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD',
    ]
  secretEnv: ["QUAY_IO_PASSWORD"]
  waitFor: ["-"]
  id: "docker-login"

- name: "gcr.io/solo-public/go-mod-make:0.4.28"
  args: ["docker-push"]
  dir: "/workspace/solo-projects"
  secretEnv: ["GITHUB_TOKEN", "QUAY_IO_PASSWORD"]
  waitFor: ["docker-login", "yarn-build"]
  id: "push-docker-images"

  # Configure Docker authentication
- name: "gcr.io/cloud-builders/gcloud"
  args: [ "auth", "configure-docker" ]
  dir: &dir "/workspace/solo-projects"
  waitFor: [ "-" ]
  id: "gcr-auth"

  # go-make is produced from https://github.com/solo-io/cloud-builders/tree/master/go-mod-make
- name: "gcr.io/solo-public/go-mod-make:0.4.28"
  args:
    [
      "init-helm",
      "build-and-upload-gcs-release-assets",
      "fetch-package-and-save-helm",
      "publish-dependencies",
    ]
  dir: *dir
  waitFor: ["prepare-workspace", "push-docker-images"]
  secretEnv: ["GITHUB_TOKEN", "QUAY_IO_PASSWORD"]
  id: "release"

  # Run make targets to retag and push docker images to GCR
- name: "gcr.io/solo-public/go-mod-make:0.4.28"
  args: ["docker-retag-images"]
  env:
    - "TEST_ASSET_ID=$_PR_NUM"
    - "ORIGINAL_IMAGE_REGISTRY=quay.io/solo-io"
    - "FINAL_IMAGE_REGISTRY=gcr.io/gloo-edge"
  dir: *dir
  secretEnv: ["GITHUB_TOKEN"]
  waitFor: ["gcr-auth", "prepare-workspace", "push-docker-images"]
  id: "docker-push-gcr"

secrets:
- kmsKeyName: projects/gloo-ee/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQAwdWthrSJ1uI5Ao/LnmX8OzXmA5TNCtDpeV6JdNouaGh5vpwSUQD5SXFIkCBvnu/wYDSGwgWNJaQV75wP/kDephn5GGuGCe0EGFXXE54zyH8iHRL45Uq0s39SoHEyYoZXF2Qla8IbKGAKswPRViYSChPthQILdA==
    QUAY_IO_PASSWORD: CiQAwdWthknPPz3v+xcbHWaCRhuSisUqPrkn6sQJxbo7SaI9iucSaQD5SXFILt6uY5C4xcuuzDcZXml2FXnRBg9Uk6BDJebycORdyslJz9iVEWeTrFZoOyHh5aDTLQhuNEmW4znFnleICVdasJtwFE9VIJCU5OGCgkTFdfGGvMx8up37ST9MwDYUPCB1vqLL1w==
    NPM_TOKEN: CiQAwdWthsrcxx34V1hGZL7uH3KcYsp9n2yiXMZ/IrDKqxD8vxgSTQD5SXFI/acbV54LBG26hMvU6qtvmoSIPLdi9F2LxdJQs+kGupmD7GykLRW6eWqJs8UJQMNmMo1u+tK8YsTvja7IhqeL2+dmZSByLIcB
# Overall build timeout of 60m. The release builds take extra time for uploading and pushing artifacts. We can
# set timeouts on specific steps (prepare-workspace, tests, etc) if we want to limit the time in sections, but want a forgiving
# timeout for the final step, and the default (10m) is not enough.
timeout: 3600s

tags: ["solo-projects"]
options:
  machineType: "N1_HIGHCPU_32"
  env:
    - "TAGGED_VERSION=$TAG_NAME"
    - "PROJECT_ROOT=github.com/solo-io/solo-projects"
    - "HELM_HOME=/root/.helm"
  volumes:
    - name: "gopath"
      path: "/go"
    - name: "ssh"
      path: /root/.ssh
