steps:

# Setup SSH
# These are required before dep
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ci/id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=build
  - --key=build-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'get-ssh-key'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv ./ci/github_known_hosts /root/.ssh/known_hosts
    git config --global url."ssh://git@github.com/solo-io".insteadOf https://github.com/solo-io
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'configure-git'

- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/solo-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'dep'

- name: 'gcr.io/$PROJECT_ID/go-make'
  entrypoint: 'bash'
  args: ['-c', 'tar -zvcf solo-projects-dep.tar.gz ./gopath/pkg/dep']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/solo-projects'
  - 'GOPATH=/workspace/gopath'
  id: 'tar-cache'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'solo-projects-dep.tar.gz', 'gs://gloo-ee-cache/solo-projects']
  id: 'upload-cache'

timeout: 1800s