steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  # if TAG_NAME is set then this is a release and we don't run tests
  args:
    - '-c'
    - 'if [ -z "$TAG_NAME" ]; then gcloud builds submit --config=ci/cloudbuild/run-tests.yaml --substitutions TAG_NAME=$TAG_NAME,COMMIT_SHA=$COMMIT_SHA,REPO_NAME=$REPO_NAME,_GO_VERSION=1.20.1; fi'
  waitFor: [ '-' ]
  id: 'run-tests'

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'builds','submit','--config=ci/cloudbuild/publish-artifacts.yaml','--substitutions','TAG_NAME=$TAG_NAME,COMMIT_SHA=$COMMIT_SHA,REPO_NAME=$REPO_NAME,_PR_NUM=$_PR_NUM,_GO_VERSION=1.20.1' ]
  waitFor: [ '-' ]
  id: 'publish-artifacts'

# Overall build timeout of 60m. The release builds take extra time for uploading and pushing artifacts. We can
# set timeouts on specific steps (prepare-workspace, tests, etc) if we want to limit the time in sections, but want a forgiving
# timeout for the final step, and the default (10m) is not enough.
timeout: 3600s

tags: ["solo-projects"]
options:
  machineType: "N1_HIGHCPU_32"
  env:
    - "TAGGED_VERSION=$TAG_NAME"
    - "PROJECT_ROOT=github.com/solo-io/solo-projects"
    - "HELM_HOME=/root/.helm"
  volumes:
    - name: "gopath"
      path: "/go"
    - name: "ssh"
      path: "/root/.ssh"
