[prune]
  go-tests = true
  unused-packages = true

# used for older sqoop, remove if upgrading to 99designs
[[constraint]]
  revision = "6b3b338d5f9c8b5a80ad4ea1e2e37aa58677ea9d"
  name = "github.com/vektah/gqlgen"

# this must match the version of the gqlgen binary we depend on

[[constraint]]
  version = "v0.6.0"
  name = "github.com/99designs/gqlgen"

[[constraint]]
  revision = "676016db8193d83324a507a986a78cd3642ad713"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  version = "1.1.1"
  name = "github.com/gogo/protobuf"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.0"

[[override]]
  version = "1.2.0"
  name = "github.com/golang/protobuf"


[[constraint]]
  name = "github.com/solo-io/envoy-operator"
  revision = "c71f318a203bca8433268be67336086379a2bf9f"


[[constraint]]
  name = "github.com/solo-io/rate-limiter"
  revision = "32838befd54a98ecd76e6f1bf0ca6df602646a04"


[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.2.13"

[[constraint]]
  name = "github.com/solo-io/gloo"
  branch = "master"

# go versioning story not ideal, so we have to pin serf to the version consul expects
[[override]]
  name = "github.com/hashicorp/serf"
  revision = "19bbd39e421bdf3559d5025fb2c760f5ffa56233"

[[constraint]]
  name = "github.com/solo-io/go-checkpoint"
  version = "0.0.4"

[[constraint]]
  name = "github.com/solo-io/keygen"
  version = "0.1.0"