ignored = ["github.com/lyft/protoc-gen-validate*"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  version = "1.1.1"
  name = "github.com/gogo/protobuf"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.13.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "github.com/Masterminds/sprig"
  version = "v2.17.0"


[[override]]
  name = "k8s.io/helm"
  version = "v2.13.0"

[[override]]
  version = "1.2.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/envoy-operator"
  version = "0.1.0"

[[constraint]]
  name = "github.com/solo-io/rate-limiter"
  revision = "5cbd4d452dccb9492a4d126f79dfcc7be43f88dc"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.10.10"

[[constraint]]
  name = "github.com/solo-io/gloo"
  version = "0.18.17"

[[override]]
  name = "github.com/hashicorp/consul"
  revision = "eba25a143821cec25bdb48fe64dd7b7a6152d01d"

# go versioning story not ideal, so we have to pin serf to the version consul expects
[[override]]
  name = "github.com/hashicorp/serf"
  revision = "19bbd39e421bdf3559d5025fb2c760f5ffa56233"

[[constraint]]
  name = "github.com/solo-io/go-checkpoint"
  version = "0.1.0"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "0.9.17"

[[constraint]]
  name = "github.com/solo-io/licensing"
  version = "0.1.1"

[[constraint]]
  name = "go.opencensus.io"
  version = "v0.19.0"

[[constraint]]
  name = "github.com/solo-io/ext-auth-service"
  version = "v0.2.7"

[[constraint]]
  version = ">=0.8.2"
  name = "github.com/envoyproxy/go-control-plane"

[[override]]
  # use v0.0.15 when it is released
  # version = "v0.0.15"
  revision = "9b492f1473afa33350d86b62c298b45da868a33f"
  name = "github.com/envoyproxy/protoc-gen-validate"

[[override]]
  name = "go.opencensus.io"
  version = "v0.22.0"

[[override]]
  name = "k8s.io/klog"
  revision = "9cbb78b20423182f9e5b2a214dd255f5e117d2d1"
  source = "github.com/stefanprodan/klog"