apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: serviceentry-test
  namespace: default
spec:
  gatewayClassName: gloo-gateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 8080
    protocol: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1:1.0
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: helloworld-v1-serviceentry
spec:
  hosts:
  - helloworld.local
  ports:
  - number: 5000
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: helloworld
      version: v1

