changelog:
  - type: DEPENDENCY_BUMP
    dependencyOwner: cncf
    dependencyRepo: containerd
    dependencyTag: v1.4.11
  - type: DEPENDENCY_BUMP
    dependencyOwner: docker
    dependencyRepo: docker/cli
    dependencyTag: v20.10.10 
  - type: DEPENDENCY_BUMP
    dependencyOwner: solo-io
    dependencyRepo: gloo 
    dependencyTag: v1.9.2