changelog:
  - type: NON_USER_FACING
    issueLink: https://github.com/solo-io/solo-projects/issues/5909
    resolvesIssue: false
    description: >-
      Add new DataPlaneConfig CRD with initial barebones API, to allow configuration of dynamically provisioned proxies
      in Gloo Gateway.
