# This is used if gloo-fed is NOT enabled, i.e. we are using the single-cluster Gloo apiserver
# TODO change the ServiceAccount name once we split out the single-cluster Gloo apiserver into its own helm chart
{{- if not .Values.enabled }}
{{- if .Values.glooFedApiserver.enable }}
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-console
  labels:
    app: gloo
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - proxies
  - settings
  - upstreams
  - upstreamgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.solo.io
  resources:
  - gateways
  - routetables
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.gloo.solo.io
  resources:
  - authconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.api.solo.io
  resources:
  - ratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-console
  labels:
    app: gloo
subjects:
- kind: ServiceAccount
  name: gloo-fed-console
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-console
  apiGroup: rbac.authorization.k8s.io

---

# For reading envoy config dumps
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-console
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - get

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-console
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gloo-console
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gloo-fed-console
  namespace: {{ .Release.Namespace }}

{{- end }} {{/* .Values.rbac.create */}}
{{- end }} {{/* .Values.glooFedApiserver.enable */}}
{{- end }} {{/* not .Values.enabled */}}