{{- $licenseKey := coalesce .Values.licenseKey .Values.license_key .Values.license.key }}
{{ if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo-fed
    gloo-fed: license
  name: gloo-fed-license
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license-key: {{ $licenseKey | b64enc | quote }}
{{- end }}
