dependencies:
  - name: gloo
    # repository: https://storage.googleapis.com/solo-public-helm
    # keep for referencing gloo-branches
    repository: https://storage.googleapis.com/solo-public-tagged-helm
    version: 1.15.0-beta21-8484 # format: <version>-<gloo PR>. Search through above url for your PR to find the full version string
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 15.18.0
    condition: prometheus.enabled
    tags:
      - monitoring
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.16.14
    condition: grafana.defaultInstallationEnabled
    tags:
      - monitoring
  - name: gloo-fed
    repository: https://storage.googleapis.com/gloo-fed-helm
