########################################################################
###                                                                  ###
###                        Settings                                  ###
###                                                                  ###
########################################################################

# Enable creation of the GlooE settings template, disable the Gloo one (see below)
settings:
  create: true

########################################################################
###                                                                  ###
###                        Gloo                                      ###
###                                                                  ###
########################################################################

license_key: ""
gloo:
  rbac:
    create: true
  settings:
    # Do not render the Gloo settings template. We would need to template out 'namespace' in a subchart value file,
    # which is hard. We will provide out own settings template as part of the GlooE chart.
    create: false
  gloo:
    deployment:
      stats: true
      image:
        repository: gloo-ee
      replicas: 1
  gatewayProxies:
    gatewayProxyV2:
      kind:
        deployment:
          replicas: 1
      podTemplate:
        stats: true
        httpPort: 8080
        httpsPort: 8443
        image:
          repository: gloo-ee-envoy-wrapper
      service:
        type: LoadBalancer
        # clusterIP: None
        httpPort: 80
        httpsPort: 443
        extraAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "8081"
        extraPorts:
          - containerPort: 8081
            name: stats
            protocol: TCP
  discovery:
    deployment:
      image:
        repository: discovery
        registry: quay.io/solo-io
  gateway:
    deployment:
      image:
        repository: gateway
        registry: quay.io/solo-io
    enabled: true
    updateValues: true
    conversionJob:
      image:
        repository: gateway-conversion
      restartPolicy: Never

########################################################################
###                                                                  ###
###                        Rate Limit                                ###
###                                                                  ###
########################################################################

rateLimit:
  # setting to false will disable rate limiting
  enabled: true
  deployment:
    stats: true
    name: "rate-limit"
    image:
      repository: rate-limit-ee
    glooAddress: gloo:9977
    redisUrl: redis:6379
  service:
    port: 18081
    name: rate-limit

redis:
  deployment:
    name: redis
    image:
      tag: "5"
      repository: redis
      registry: docker.io
    staticPort: 6379
  service:
    port: 6379
    name: redis

########################################################################
###                                                                  ###
###                        API Server                                ###
###                                                                  ###
########################################################################

apiServer:
  enableBeta: true
  deployment:
    stats: true
    name: "grpcserver-ui"
    server:
      image:
        name: apiserver
        repository: grpcserver-ee
      grpcPort: 10101
      oauth: {}
    ui:
      image:
        name: "gloo-ui"
        repository: grpcserver-ui
      staticPort: 8080
    envoy:
      image:
        name: "grpcserver-envoy"
        repository: grpcserver-envoy
  service:
    name: "apiserver-ui"

########################################################################
###                                                                  ###
###                        Observability                             ###
###                                                                  ###
########################################################################

observability:
  deployment:
    stats: true
    name: observability
    image:
      repository: observability-ee

########################################################################
###                                                                  ###
###                        GLOBAL                                    ###
###                                                                  ###
########################################################################

global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
    pullSecret: solo-io-readerbot-pull-secret
  extensions:
    extAuth:
      envoySidecar: false
      userIdHeader: x-user-id
      deployment:
        stats: true
        name: "extauth"
        image:
          repository: extauth-ee
        port: 8083
      service:
        port: 8083
        name: extauth
      signingKey:
        name: extauth-signing-key
        signing-key: ""

########################################################################
###                                                                  ###
###                        RBAC                                      ###
###                                                                  ###
########################################################################

rbac:
  create: true

########################################################################
###                                                                  ###
###                        Prometheus                                ###
###                                                                  ###
########################################################################

prometheus:
  # setting to false will disable prometheus, removing it from gloo's chart dependencies
  enabled: true
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: false
  server:
    persistentVolume:
      size: 16Gi
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

########################################################################
###                                                                  ###
###                        Grafana                                   ###
###                                                                  ###
########################################################################

grafana:
  # setting to false will disable grafana, removing it from gloo's chart dependencies
  enabled: true
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 100Mi
  rbac:
    pspUseAppArmor: false
  datasources:
    datasources.yaml:
      # config file version
      apiVersion: 1
      # list of datasources to insert/update depending
      # what's available in the database
      datasources:
        # <string, required> name of the datasource. Required
        - name: gloo
          # <string, required> datasource type. Required
          type: prometheus
          access: proxy
          url: http://glooe-prometheus-server:80
          isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "gloo"
          orgId: 1
          folder: "gloo"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/gloo
  dashboardsConfigMaps:
    gloo: glooe-grafana-custom-dashboards
  grafana.ini:
    server:
      domain: glooe-grafana
      root_url: "%(protocol)s://%(domain)s/grafana/"
