{{- if .Values.gateway2.controlPlane.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gloo-gateway.controlPlane.fullname" . }}
  labels:
    {{- include "gloo-gateway.gateway.const_labels" . | nindent 4 }}
    {{- include "gloo-gateway.controlPlane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway2.controlPlane.replicaCount }}
  selector:
    matchLabels:
      {{- include "gloo-gateway.controlPlane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.gateway2.controlPlane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gloo-gateway.controlPlane.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.gateway2.controlPlane.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gloo-gateway.controlPlane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway2.controlPlane.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.gateway2.controlPlane.securityContext | nindent 12 }}
          image: "{{ .Values.gateway2.controlPlane.image.repository }}:{{ .Values.gateway2.controlPlane.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway2.controlPlane.image.pullPolicy }}
          args:
          - controller
          - "--class-name"
          - "{{ .Values.gateway2.gatewayClass.className }}"
          - "--controller-name"
          - "{{ .Values.gateway2.gatewayClass.controllerName }}"
          {{- if .Values.gateway2.develop }}
          - "--dev-mode"
          {{- end }}
          {{- if .Values.gateway2.controlPlane.autoProvision }}
          - "--auto-provision"
          {{- end }}
          - --xds-server
          - {{ printf "%s.%s" (include "gloo-gateway.controlPlane.fullname" . ) .Release.Namespace }}
          - --xds-port
          - "{{ .Values.gateway2.controlPlane.service.port }}"
          - --release-name={{ .Release.Name }}
          ports:
            - name: health
              containerPort: 9093
              protocol: TCP
            - name: metrics
              containerPort: 9092
              protocol: TCP
            - name: http
              containerPort: {{ .Values.gateway2.controlPlane.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.gateway2.controlPlane.resources | nindent 12 }}
      {{- with .Values.gateway2.controlPlane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway2.controlPlane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway2.controlPlane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
