{{- if .Values.rateLimit.enabled }}
{{- range $name, $spec := .Values.gloo.gatewayProxies }}
{{- $redisName := $.Values.redis.service.name }}
{{- if $.Values.global.extensions.dataplanePerProxy }}
{{- $redisName = printf "%s-%s" $redisName ($name | kebabcase) }}
{{- end }} # .Values.global.extensions.dataplanePerProxy
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ $redisName }}
  name: {{ $redisName }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: redis
      port: {{ $.Values.redis.service.port }}
      protocol: TCP
  selector:
    gloo: {{ $redisName }}
---
{{- end }} # range $name, $spec := .Values.gatewayProxies
{{- end }} # .Values.rateLimit.enabled