{{- if .Values.rateLimit.enabled }}
{{- include "gloo.dataplaneperproxyhelper" $ }}
{{- range $name, $spec := $.ProxiesToCreateDataplaneFor }}
{{- if not $spec.disabled}}
{{- $redisName := $.Values.redis.service.name }}
{{- if $.Values.global.extensions.dataplanePerProxy }}
{{- $redisName = printf "%s-%s" $redisName ($name | kebabcase) }}
{{- end }} {{/* .Values.global.extensions.dataplanePerProxy */}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ $redisName }}
  name: {{ $redisName }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: redis
      port: {{ $.Values.redis.service.port }}
      protocol: TCP
  selector:
    gloo: {{ $redisName }}
  {{- if $.Values.redis.clientSideShardingEnabled }}
  clusterIP: "None" {{/* Headless Service so Envoy can LB between Redis instances */}}
  {{- end }}
---
{{- end }} {{/* if not $spec.disabled */}}
{{- end }} {{/* range $name, $spec := $.ProxiesToCreateDataplaneFor */}}
{{- end }} {{/* .Values.rateLimit.enabled */}}