{{- if .Values.rateLimit.enabled }}
{{- $image := .Values.redis.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.redis.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: redis
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: redis
      {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
      installationId: {{ include "gloo.installationId" $installationContext }}
  template:
    metadata:
      labels:
        gloo: redis
        {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
        installationId: {{ include "gloo.installationId" $installationContext }}
    spec:
      containers:
        - image: {{template  "gloo.image" $image}}
          imagePullPolicy:  {{ $image.pullPolicy }}
          name: redis
          ports:
            - containerPort: {{ .Values.redis.deployment.staticPort }}
          env:
            - name: MASTER
              value: "true"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      volumes:
        - name: data
          emptyDir: {}
{{- end }}