{{- if .Values.rateLimit.enabled }}
{{- $image := merge .Values.redis.deployment.image .Values.global.image }}
{{- include "gloo.dataplaneperproxyhelper" $ }}
{{- range $name, $spec := $.ProxiesToCreateDataplaneFor }}
{{- if not $spec.disabled }}
{{- $redisName := $.Values.redis.deployment.name }}
{{- if $.Values.global.extensions.dataplanePerProxy }}
{{- $redisName = printf "%s-%s" $redisName ($name | kebabcase) }}
{{- end }} {{/* .Values.global.extensions.dataplanePerProxy */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: {{ $redisName }}
  name: {{ $redisName }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- if not (kindIs "invalid" $.Values.redis.deployment.replicas) }}
  replicas: {{ $.Values.redis.deployment.replicas }}
{{- end }}
  selector:
    matchLabels:
      gloo: {{ $redisName }}
  template:
    metadata:
      labels:
        gloo: {{ $redisName }}
        {{- if $.Values.redis.deployment.extraRedisLabels }}
        {{- range $key, $value := $.Values.redis.deployment.extraRedisLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - image: {{template "glooe.imagenonextended" $image}}
          imagePullPolicy:  {{ $image.pullPolicy }}
          name: redis
          ports:
            - containerPort: {{ $.Values.redis.deployment.staticPort }}
          env:
            - name: MASTER
              value: "true"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
          {{- if $.Values.redis.deployment.resources }}
          resources:
{{ toYaml $.Values.redis.deployment.resources | indent 12}}
          {{- end}}
      {{- include "gloo.pullSecret" $image | nindent 6}}
      securityContext:
        runAsNonRoot: true
        runAsGroup: {{ printf "%.0f" (float64 $.Values.redis.deployment.runAsGroup) }}
        fsGroup: {{ printf "%.0f" (float64 $.Values.redis.deployment.fsGroup) }}
        {{- if not $.Values.redis.deployment.floatingUserId }}
        runAsUser: {{ printf "%.0f" (float64 $.Values.redis.deployment.runAsUser) -}}
        {{- end }}
      volumes:
        - name: data
          emptyDir: {}
---
{{- end }} {{/* if not $spec.disabled */}}
{{- end }} {{/* range $name, $spec := $.ProxiesToCreateDataplaneFor */}}
{{- end }} {{/* .Values.rateLimit.enabled */}}
