apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: redis
  template:
    metadata:
      labels:
        gloo: redis
    spec:
      containers:
        - image: "{{ .Values.redis.deployment.image.repository }}:{{ .Values.redis.deployment.image.tag }}"
          imagePullPolicy:  {{ .Values.redis.deployment.image.pullPolicy }}
          name: redis
          ports:
            - containerPort: {{ .Values.redis.deployment.staticPort }}
          env:
            - name: MASTER
              value: "true"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      {{- if  .Values.redis.deployment.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.redis.deployment.image.pullSecret }}{{end}}
      volumes:
        - name: data
          emptyDir: {}
