{{- if .Values.rbac.create }}

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-ee-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-ee-role
  apiGroup: rbac.authorization.k8s.io

{{- end -}}
