{{- if .Values.rateLimit.enabled }}
{{- $image := .Values.rateLimit.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.rateLimit.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: rate-limit
  name: rate-limit
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: rate-limit
  template:
    metadata:
      labels:
        gloo: rate-limit
      {{- if .Values.rateLimit.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      containers:
        - image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: rate-limit
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GLOO_ADDRESS
              value: {{ .Values.rateLimit.deployment.glooAddress }}
            - name: REDIS_URL
              value: {{ .Values.rateLimit.deployment.redisUrl }}
            - name: REDIS_SOCKET_TYPE
              value: tcp
            {{- if .Values.rateLimit.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}}
      {{- if $image.pullSecret }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      {{- end }}
{{- end }}