{{- if .Values.rateLimit.enabled }}
{{- $image := .Values.rateLimit.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.rateLimit.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: rate-limit
  name: rate-limit
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: rate-limit
  template:
    metadata:
      labels:
        gloo: rate-limit
      {{- if .Values.rateLimit.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      containers:
        - image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: rate-limit
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GLOO_ADDRESS
              value: {{ .Values.rateLimit.deployment.glooAddress }}
            - name: SERVICE_NAME
              value: {{.Values.rateLimit.serviceName}}
            {{- if .Values.rateLimit.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}}
            {{- if .Values.rateLimit.deployment.dynamodb.secretName }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rateLimit.deployment.dynamodb.secretName }}
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rateLimit.deployment.dynamodb.secretName }}
                  key: aws_secret_access_key
            - name: AWS_REGION
              value: {{ .Values.rateLimit.deployment.dynamodb.region }}
            - name: DYNAMODB_RATE_LIMIT_TABLE_NAME
              value: {{ .Values.rateLimit.deployment.dynamodb.tableName }}
            - name: DYNAMODB_CONSISTENT_READS
              value: {{ .Values.rateLimit.deployment.dynamodb.consistentReads | quote }}
            - name: DYNAMODB_BATCH_SIZE
              value: {{ .Values.rateLimit.deployment.dynamodb.batchSize | quote }}
            {{- else }} # .Values.rateLimit.deployment.dynamodb.secretName
            - name: REDIS_URL
              value: {{ .Values.rateLimit.deployment.redisUrl }}
            - name: REDIS_SOCKET_TYPE
              value: tcp
            {{- end }} # .Values.rateLimit.deployment.dynamodb.secretName
      {{- if $image.pullSecret }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      {{- end }}
{{- end }}