{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}
{{- if or $extAuth.standaloneDeployment $extAuth.envoySidecar }}
{{- if not $extAuth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo
    gloo: extauth
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: {{ $extAuth.signingKey.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if $extAuth.signingKey.key }}
  signing-key: {{ $extAuth.signingKey.key | b64enc | quote }}
  {{- else }}
  signing-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }} # if signingKey.key
{{- end -}} # if not existingsecret
{{- end}} # if standalone or sidecar
{{- end}} # enabled
