{{- $image := .Values.extAuth.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.extAuth.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.extAuth.deployment.name }}
  name: {{ .Values.extAuth.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: {{ .Values.extAuth.deployment.name }}
  template:
    metadata:
      labels:
        gloo: {{ .Values.extAuth.deployment.name }}
      {{- if .Values.extAuth.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      containers:
        - image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          name: {{ .Values.extAuth.deployment.name }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GLOO_ADDRESS
  {{- if .Values.extAuth.deployment.glooAddress }}
              value: {{ .Values.extAuth.deployment.glooAddress }}
  {{- else }}
              value: gloo:{{ .Values.gloo.gloo.deployment.xdsPort }}
  {{- end }}
            - name: SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.extAuth.signingKey.name }}
                  key: signing-key
            {{- if .Values.extAuth.deployment.debugPort }}
            - name: DEBUG_PORT
              value: {{ .Values.extAuth.deployment.debugPort  | quote }}
            {{- end }}
            {{- if .Values.extAuth.deployment.port }}
            - name: SERVER_PORT
              value: {{ .Values.extAuth.deployment.port  | quote }}
            {{- end }}
            {{- if .Values.extAuth.userIdHeader }}
            - name: USER_ID_HEADER
              value: {{ .Values.extAuth.userIdHeader  | quote }}
            {{- end }}
            {{- if .Values.extAuth.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}}
      {{- if $image.pullSecret }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      {{- end }}