{{- $extAuth := .Values.global.extensions.extAuth }}
{{- if not $extAuth.envoySidecar }}
{{- $image := $extAuth.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge $extAuth.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.deployment.name }}
  name: {{ $extAuth.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: {{ $extAuth.deployment.name }}
  template:
    metadata:
      labels:
        gloo: {{ $extAuth.deployment.name }}
      {{- if $extAuth.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      {{- if $extAuth.plugins }}
      volumes:
      - emptyDir: {}
        name: auth-plugins
      initContainers:
      {{- range $name, $plugin := $extAuth.plugins }}
      {{- $pluginImage := merge $plugin.image $.Values.global.image }}
      - image: {{template "gloo.image" $pluginImage}}
        {{- if $pluginImage.pullPolicy }}
        imagePullPolicy: {{ $pluginImage.pullPolicy }}
        {{- end}}
        name: plugin-{{ $name }}
        volumeMounts:
          - name: auth-plugins
            mountPath: /auth-plugins
      {{- end}}
      {{- end}}
      containers:
      {{- include "gloo.extauthcontainer" . | nindent 6 }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    gloo: gateway-proxy
                topologyKey: kubernetes.io/hostname
  {{- end}}