{{- if .Values.global.extensions.extAuth.enabled }}
{{- if .Values.global.extensions.extAuth.standaloneDeployment }}
{{- $extAuth := .Values.global.extensions.extAuth }}
{{- $image := $extAuth.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge $extAuth.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.deployment.name }}
  name: {{ $extAuth.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: {{ $extAuth.deployment.name }}
  template:
    metadata:
      labels:
        gloo: {{ $extAuth.deployment.name }}
      {{- if $extAuth.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}} # $extAuth.deployment.stats
    spec:
      {{- if $extAuth.plugins }}
      volumes:
      {{- include "gloo.extauthpluginvolume" . | nindent 6 }}
      initContainers:
      {{- include "gloo.extauthinitcontainers" . | nindent 6 }}
      {{- end}} # $extAuth.plugins
      containers:
      {{- $data := dict "Values" .Values "ExtAuthMode" "standalone" -}}
      {{- include "gloo.extauthcontainer" $data | nindent 6 }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    gloo: gateway-proxy
                topologyKey: kubernetes.io/hostname
{{- end}} # .Values.global.extensions.extAuth.standaloneDeployment
{{- end}} # enabled
