{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}
{{- if $extAuth.standaloneDeployment }}
{{- range $name, $spec := .Values.gloo.gatewayProxies }}
{{- $extAuthName := $extAuth.service.name }}
{{- if $.Values.global.extensions.dataplanePerProxy }}
{{- $extAuthName = printf "%s-%s" $extAuthName ($name | kebabcase) }}
{{- end }} # .Values.global.extensions.dataplanePerProxy
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuthName }}
  name: {{ $extAuthName }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ $extAuth.service.port }}
    protocol: TCP
  selector:
    gloo: {{ $extAuthName }}
---
{{- end }} # range $name, $spec := .Values.gatewayProxies
{{- end }} # enabled
{{- end }} # .Values.global.extensions.extAuth.standaloneDeployment
