{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}
{{- if $extAuth.standaloneDeployment }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.service.name }}
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: {{ $extAuth.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ $extAuth.service.port }}
    protocol: TCP
  selector:
    gloo: {{ $extAuth.service.name }}
{{- end }}
{{- end }} # enabled
