apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.extAuth.service.name }}
  name: {{ .Values.extAuth.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.extAuth.service.port }}
    protocol: TCP
  selector:
    gloo: {{ .Values.extAuth.service.name }}
