{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}

{{- if $extAuth.envoySidecar }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.service.name }}
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: {{ $extAuth.service.name }}-sidecar
  namespace: {{ .Release.Namespace }}
spec:
  upstreamSpec:
    use_http2: true
    pipe:
      path: "/usr/share/shared-data/.sock"
{{- end }}
---
{{- if $extAuth.standaloneDeployment }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.service.name }}
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: {{ $extAuth.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  upstreamSpec:
    use_http2: true
    healthChecks:
    - timeout: 5s
      interval: 1m
      unhealthyThreshold: 5
      healthyThreshold: 5
      grpcHealthCheck:
        serviceName: {{ $extAuth.serviceName }}
    kube:
      serviceName: {{ $extAuth.service.name }}
      serviceNamespace: {{ .Release.Namespace }}
      servicePort:  {{ $extAuth.service.port }}
      serviceSpec:
        grpc: {}
{{- end }}
{{- end }}
