{{- if .Values.global.extensions.extAuth.enabled }}
{{- $extAuth := .Values.global.extensions.extAuth }}
{{- $extAuthName := $extAuth.service.name }}

{{- if $extAuth.envoySidecar }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuthName }}
  name: {{ $extAuthName }}-sidecar
  namespace: {{ $.Release.Namespace }}
spec:
  use_http2: true
  pipe:
    path: "/usr/share/shared-data/.sock"
{{- end }}
---
{{- if $extAuth.standaloneDeployment }}
{{- range $name, $spec := .Values.gloo.gatewayProxies }}
{{- if $.Values.global.extensions.dataplanePerProxy }}
{{- $extAuthName = printf "%s-%s" $extAuth.service.name ($name | kebabcase) }}
{{- end }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuthName }}
  name: {{ $extAuthName }}
  namespace: {{ $.Release.Namespace }}
spec:
  use_http2: true
  healthChecks:
  - timeout: 5s
    interval: 10s
    unhealthyThreshold: 3
    healthyThreshold: 3
    grpcHealthCheck:
      serviceName: {{ $extAuthName }}
  kube:
    serviceName: {{ $extAuthName }}
    serviceNamespace: {{ $.Release.Namespace }}
    servicePort:  {{ $extAuth.service.port }}
    serviceSpec:
      grpc: {}
  {{- if $.Values.global.glooMtls.enabled }}
  sslConfig:
    secretRef:
      name: gloo-mtls-certs
      namespace: gloo-system
  {{- end }}
---
{{- end }} # range $name, $spec := .Values.gatewayProxies
{{- end }} # $extAuth.standaloneDeployment
{{- end }} # .Values.global.extensions.extAuth.enabled
