{{- $extAuth := .Values.global.extensions.extAuth }}
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: {{ $extAuth.service.name }}
  name: {{ $extAuth.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  upstreamSpec:
    use_http2: true
    {{- if $extAuth.envoySidecar }}
    pipe:
      path: "/usr/share/shared-data/.sock"
    {{- else }}
    healthChecks:
    - timeout: 5s
      interval: 1m
      unhealthyThreshold: 5
      healthyThreshold: 5
      grpcHealthCheck:
        serviceName: {{ $extAuth.serviceName }}
    kube:
      serviceName: {{ $extAuth.service.name }}
      serviceNamespace: {{ .Release.Namespace }}
      servicePort:  {{ $extAuth.service.port }}
      serviceSpec:
        grpc: {}
    {{- end }}