{{- if .Values.gloo.gateway.updateValues -}}
{{- include "gloo.updatevalues" . -}}
{{- end -}}
{{- $redisPassword := "" }}
{{- if .Values.global.extensions.glooRedis.enableAcl -}}
{{- $old_sec := lookup "v1" "Secret" .Release.Namespace "redis" }}
{{- if not $old_sec.data }}
{{- $redisPassword = randAlphaNum 64 }}
{{- else }}
{{- $redisPassword = index $old_sec.data "redis-password" | b64dec }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo
    gloo: redis
  name: redis
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  users.acl: {{ list .Values.redis.aclPrefix $redisPassword | join "" | b64enc }}
  redis-password: {{ $redisPassword | b64enc }}
{{- end }}
---
{{- if or .Values.global.glooMtls.enabled $.Values.redis.clientSideShardingEnabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limit-sidecar-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: gloo
    gloo: gloo
data:
  envoy-sidecar.yaml: |
    node:
      id: sds_client
      cluster: sds_client
    static_resources:
      listeners:
      {{- if .Values.global.glooMtls.enabled }}
      {{- include "gloo.sidecarlisteners" $ | nindent 6 }}
      {{- end }}
      {{- if $.Values.redis.clientSideShardingEnabled }}
      - name: redis_listener
        address:
          pipe:
            path: /var/run/envoy/ratelimit.sock
        filter_chains:
        - filters:
          - name: envoy.filters.network.redis_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
              stat_prefix: ratelimit_redis
              settings:
                op_timeout: 5s
              prefix_routes:
                catch_all_route:
                  cluster: redis_cluster
              {{- if .Values.global.extensions.glooRedis.enableAcl }}
              downstream_auth_password:
                inline_string: {{ $redisPassword }}
              {{- end }}
      {{- end }}
      clusters:
      {{- if $.Values.redis.clientSideShardingEnabled }}
      - name: redis_cluster
        connect_timeout: 1s
        type: STRICT_DNS
        lb_policy: MAGLEV
        outlier_detection:
          consecutive_5xx: 10
        health_checks:
        - timeout: 1s
          interval: 1s
          no_traffic_interval: 5s
          interval_jitter: 1s
          unhealthy_threshold: 1
          healthy_threshold: 1
          custom_health_check:
            name: envoy.health_checkers.redis
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
        load_assignment:
          cluster_name: redis_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: redis
                    port_value: 6379
        {{- if .Values.global.extensions.glooRedis.enableAcl }}
        typed_extension_protocol_options:
          envoy.filters.network.redis_proxy:
            "@type": type.googleapis.com/google.protobuf.Struct
            value:
              auth_password:
                inline_string: {{ $redisPassword }}
        {{- end }}
      {{- end }}
      {{- if .Values.global.glooMtls.enabled }}
      - name: gloo_client_sds
        connect_timeout: 0.25s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: gloo_client_sds
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8234
      - name: gloo.{{ $.Release.Namespace }}.svc.{{ .Values.gloo.k8s.clusterName }}:{{ .Values.global.extensions.rateLimit.deployment.glooPort }}
        alt_stat_name: xds_cluster
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: gloo.{{ $.Release.Namespace }}.svc.{{ .Values.gloo.k8s.clusterName }}:{{ .Values.global.extensions.rateLimit.deployment.glooPort }}
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Values.global.extensions.rateLimit.deployment.glooAddress }}
                        port_value: {{ .Values.global.extensions.rateLimit.deployment.glooPort }}
        http2_protocol_options: {}
        upstream_connection_options:
          tcp_keepalive: {}
        type: STRICT_DNS
        respect_dns_ttl: true
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificate_sds_secret_configs:
                - name: server_cert
                  sds_config:
                    resource_api_version: V3
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        - envoy_grpc:
                            cluster_name: gloo_client_sds
              validation_context_sds_secret_config:
                name: validation_context
                sds_config:
                  resource_api_version: V3
                  api_config_source:
                    api_type: GRPC
                    transport_api_version: V3
                    grpc_services:
                      - envoy_grpc:
                          cluster_name: gloo_client_sds
      {{- end }}
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
{{- end }}