{{- if .Values.rateLimit.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ .Values.rateLimit.service.name }}
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: {{ .Values.rateLimit.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.rateLimit.service.port }}
    protocol: TCP
  selector:
    gloo: {{ .Values.rateLimit.service.name }}
{{- end }}