{{- if .Values.global.extensions.rateLimit.enabled }}
{{- include "gloo.dataplaneperproxyhelper" $ }}
{{- range $name, $spec := $.ProxiesToCreateDataplaneFor }}
{{- if not $spec.disabled }}
{{- $rateLimitName := $.Values.global.extensions.rateLimit.service.name }}
{{- if $.Values.global.extensions.dataplanePerProxy }}
{{- $rateLimitName = printf "%s-%s" $rateLimitName ($name | kebabcase) }}
{{- end }} {{/* .Values.global.extensions.dataplanePerProxy */}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: {{ $rateLimitName }}
  name: {{ $rateLimitName }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: {{ $.Values.global.extensions.rateLimit.service.port }}
    protocol: TCP
  selector:
    gloo: {{ $rateLimitName }}
---
{{- end }} {{/* if not $spec.disabled */}}
{{- end }} {{/* range $name, $spec := $.ProxiesToCreateDataplaneFor */}}
{{- end }} {{/* .Values.global.extensions.rateLimit.enabled */}}