apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo
    gloo: license
    installationId: {{ include "gloo.installationId" . }}
  name: license
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.license_key }}
  license-key: {{ .Values.license_key | b64enc | quote }}
{{- else }}
  license-key: ""
{{- end }}