apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo
    gloo: license
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
  name: license
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.license_key }}
  license-key: {{ .Values.license_key | b64enc | quote }}
{{- else }}
  license-key: ""
{{- end }}