{{- if .Values.apiServer.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: {{ .Values.apiServer.service.name }}
    {{- $installationContext := dict "Values" .Values.gloo }} # TODO: https://github.com/solo-io/gloo/issues/1635
    installationId: {{ include "gloo.installationId" $installationContext }}
spec:
  ports:
    - name: static
      port: {{.Values.apiServer.deployment.ui.staticPort}}
      protocol: TCP
  selector:
    gloo: {{ .Values.apiServer.service.name }}
  type: NodePort
{{- end }} # .Values.apiServer.enable
