{{ if .Values.settings.create }}

apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  labels:
    app: gloo
    gloo: settings
  name: default
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
spec:
  gloo:
    xdsBindAddr: "0.0.0.0:{{ .Values.gloo.gloo.deployment.xdsPort }}"
  {{- $releasenamespace := .Release.Namespace}}
  discoveryNamespace: {{ .Values.settings.writeNamespace | default $releasenamespace }}
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  refreshRate: 60s

{{- if .Values.gloo.gateway.validation }}
  gateway:
    validation:
      proxyValidationServerAddr: "gloo:{{ .Values.gloo.gloo.deployment.validationPort }}"
      alwaysAccept: {{ .Values.gloo.gateway.validation.alwaysAcceptResources }}
{{- end }}

{{- if .Values.gloo.discovery.fdsMode }}
  discovery:
    fdsMode: {{.Values.gloo.discovery.fdsMode}}
{{- end }}

  extensions:
    configs:
      {{- $extauth := .Values.global.extensions.extAuth }}
      {{- if or $extauth.envoySidecar $extauth.standaloneDeployment }}
      extauth:
        extauthzServerRef:
          # arbitrarily default to the standalone deployment name even if we're using both
          {{- if $extauth.standaloneDeployment }}
          name: extauth
          {{- else }}
          name: extauth-sidecar
          {{- end }}
          namespace: {{ .Release.Namespace }}
      {{- end }}
  ratelimitServer:
    ratelimit_server_ref:
      name: rate-limit
      namespace: {{ .Release.Namespace }}

{{- if .Values.settings.singleNamespace }}
  watchNamespaces:
    - {{ .Release.Namespace }}
{{- else }}
{{- with .Values.settings.watchNamespaces }}
  watchNamespaces:
  {{- range . }}
  - {{ . }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
