apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
    gloo: {{ .Values.apiServer.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: {{ .Values.apiServer.service.name }}
  template:
    metadata:
      labels:
        gloo: {{ .Values.apiServer.service.name }}
      {{- if .Values.apiServer.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      containers:
        - name: apiserver-ui
          image: '{{.Values.apiServer.deployment.ui.image.repository}}:{{.Values.apiServer.deployment.ui.image.tag}}'
          imagePullPolicy: {{.Values.apiServer.deployment.ui.image.pullPolicy}}
          volumeMounts:
            - name: empty-cache
              mountPath: /var/cache/nginx
            - name: empty-run
              mountPath: /var/run
          ports:
            - name: static
              containerPort: {{.Values.apiServer.deployment.ui.staticPort}}
              protocol: TCP
        - name: grpcserver
          image: '{{.Values.apiServer.deployment.server.image.repository}}:{{.Values.apiServer.deployment.server.image.tag}}'
          imagePullPolicy: {{.Values.apiServer.deployment.server.image.pullPolicy}}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GRPC_PORT
              value: '{{ .Values.apiServer.deployment.server.grpcPort }}'
            {{- if .Values.apiServer.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}} # stats
            - name: NO_AUTH
              value: "1"
            - name: GLOO_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: license
                  key: license-key
          ports:
            - name: grpcport
              containerPort: {{.Values.apiServer.deployment.server.grpcPort}}
              protocol: TCP
        - name: gloo-grpcserver-envoy
          image: '{{.Values.apiServer.deployment.envoy.image.repository}}:{{.Values.apiServer.deployment.envoy.image.tag}}'
          imagePullPolicy: {{.Values.apiServer.deployment.envoy.image.pullPolicy}}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
      volumes:
        - name: empty-cache
          emptyDir: {}
        - name: empty-run
          emptyDir: {}
      {{- if .Values.extAuth.deployment.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.extAuth.deployment.image.pullSecret }}
      {{- end }}