apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiServer.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    gloo: {{ .Values.apiServer.service.name }}
spec:
  ports:
    - name: static
{{- if .Values.apiServer.noAuth }}
      port: {{.Values.apiServer.deployment.ui.staticPortNoAuth}}
{{- else }}
      port: {{.Values.apiServer.deployment.ui.staticPort}}
{{- end}}
      protocol: TCP
  selector:
    gloo: {{ .Values.apiServer.service.name }}
  type: NodePort