{{- if .Values.gloo.gateway.rolloutJob.enabled }}
{{- $image := .Values.gloo.gateway.rolloutJob.image }}
{{- if .Values.global }}
{{- $image = merge .Values.gloo.gateway.rolloutJob.image .Values.gloo.global.image }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: resource-rollout
  name: gloo-ee-resource-rollout-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3" # run this job after the role/rolebinding is created
    {{- include "gloo.jobHelmDeletePolicySucceededAndBeforeCreation" .Values.gloo.gateway.rolloutJob | nindent 4 }}
spec:
  {{- include "gloo.jobSpecStandardFields" .Values.gloo.gateway.rolloutJob | nindent 2 -}}
  template:
    metadata:
      labels:
        gloo: resource-rollout
        sidecar.istio.io/inject: "false"
        {{- if .Values.gloo.gateway.rolloutJob.extraPodLabels }}
        {{- range $key, $value := .Values.gloo.gateway.rolloutJob.extraPodLabels }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- if or .Values.gloo.settings.linkerd .Values.gloo.gateway.rolloutJob.extraPodAnnotations }}
      annotations:
        {{- if .Values.gloo.settings.linkerd }}
        "linkerd.io/inject": disabled
        {{- end }}
        {{- range $key, $value := .Values.gloo.gateway.rolloutJob.extraPodAnnotations }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "gloo.pullSecret" $image | nindent 6 -}}
      serviceAccountName: gloo-resource-rollout
      {{- include "gloo.podSpecStandardFields" .Values.gloo.gateway.rolloutJob | nindent 6 -}}
      containers:
        - name: kubectl
          image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ $image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            {{- if not .Values.gloo.gateway.rolloutJob.floatingUserId }}
            runAsUser: {{ printf "%.0f" (float64 .Values.gloo.gateway.rolloutJob.runAsUser) -}}
            {{- end }}
          {{- with .Values.gloo.gateway.rolloutJob.resources }}
          resources: {{ toYaml . | nindent 12}}
          {{- end }}
          command:
          - /bin/sh
          - -c
          - |
            # Check if the resource rollout job exists
            kubectl -n {{ .Release.Namespace }} get job gloo-ee-resource-rollout &> /dev/null
            if [ $? -eq 0 ]
            then
              # Clean it up so it doesn't cause issues with upgrades
              kubectl -n {{ .Release.Namespace }} delete job gloo-ee-resource-rollout || exit $?
            fi
{{- end }}{{/* if .Values.gloo.gateway.rolloutJob.enabled  */}}

