{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: observability
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
  name: observability
  namespace: {{ $.Release.Namespace }}
{{- end }} # enabled
