{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: observability
  template:
    metadata:
      labels:
        gloo: observability
      {{- if .Values.observability.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      containers:
        - image: "{{.Values.observability.deployment.image.repository}}:{{.Values.observability.deployment.image.tag}}"
          imagePullPolicy: {{.Values.observability.deployment.image.pullPolicy}}
          name: observability
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GRAFANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-grafana
                  key: admin-user
            - name: GRAFANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Release.Name}}-grafana
                  key: admin-password
            {{- if .Values.observability.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}}
      {{- if .Values.observability.deployment.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.observability.deployment.image.pullSecret }}
      {{- end }}
{{- end }}