{{- if .Values.observability.enabled }}
{{- if or .Values.grafana.defaultInstallationEnabled .Values.observability.customGrafana.enabled }}
{{- $image := .Values.observability.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.observability.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: observability
  template:
    metadata:
      labels:
        gloo: observability
        app: gloo
      {{- if .Values.observability.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      serviceAccountName: observability
      volumes:
        - name: upstream-dashboard-template
          configMap:
            name: {{ .Release.Name }}-observability-config
            items:
            - key: DASHBOARD_JSON_TEMPLATE
              path: dashboard-template.json
      containers:
        - image: {{template "gloo.image" $image}}
          imagePullPolicy: {{$image.pullPolicy}}
          name: observability
          volumeMounts:
            - name: upstream-dashboard-template
              mountPath: /observability
              readOnly: true
          env:
            - name: GLOO_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: license
                  key: license-key
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-observability-config
            - secretRef:
                name: {{.Release.Name}}-observability-secrets
            {{- if .Values.observability.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
            {{- end}}
      {{- if $image.pullSecret }}
      imagePullSecrets:
        - name: {{ $image.pullSecret }}
      {{- end }}
{{- end }}
{{- end }} # enabled
