changelog:
  - type: FIX
    issueLink: https://github.com/solo-io/gloo/issues/6722
    resolvesIssue: false
    description: |
      Add missing RBAC permissions that are needed to read Settings CR when Gloo Fed is enabled.
