changelog:
- type: FIX
  description: >
    With `disableProxyCollection: false` (the default), extauth had a race condition
    where it could recevie nil config. This could result in 403s that shouldn't happen.
    This change pulls in a fix from gloo where an empty snapshot was being set with an empty version.
    Fixing this issue means that this nil config should no longer occur.
  issueLink: https://github.com/solo-io/gloo/issues/2645
- type: DEPENDENCY_BUMP
  dependencyOwner: solo-io
  dependencyRepo: solo-kit
  dependencyTag: v0.13.3
- type: DEPENDENCY_BUMP
  dependencyOwner: solo-io
  dependencyRepo: gloo
  dependencyTag: v1.3.15