arrowParens: avoid
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: css
jsxSingleQuote: true
parser: 'typescript'
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'es5'
useTabs: false
bracketSameLine: true
printWidth: 125
