name: CI
on: pull_request
jobs:
  codegen:
    name: codegen check
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Configure git for private modules
        env:
          # matches the GITHUB_ACTION secret used in the cloudbuild, but named CI_ADMIN_GITHUB_TOKEN here
          # because secrets.GITHUB_ACTION is reserved in github workflows
          TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
        run: git config --global url."https://soloio_bot:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Yarn Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd projects/ui install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Generate Code
        run: |
          ./ci/check-code-gen.sh