name: EKS Cluster Deletion
run-name: Delete CI EKS clusters
on:
  workflow_dispatch:
    inputs:
      environment_id:
        description: "Environment ID - Found as part of the cluster name: 'cicd-< Environment ID >:<region>'"
        required: true
        default: edge-scale

jobs:
  cleanup-environment:
    uses: solo-io/gloo-eng-test-beds/.github/workflows/cleanup-eng-env.yaml@main
    with:
      environment: eks-developers-acct
      cluster-group: cicd-${{ github.event.inputs.environment_id }}
    secrets:
      GIT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}