name: Fed Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 1-5" # weekdays @ 00:00 EST, run tests against latest dev
    - cron: "6 6 * * 1"   # monday   @ 01:06 EST, run expanded tests against v1.13.x 
    - cron: "7 7 * * 1"   # monday   @ 02:07 EST, run expanded tests against v1.12.x
    - cron: "8 8 * * 1"   # monday   @ 03:08 EST, run expanded tests against v1.11.x
    - cron: "9 9 * * 1"   # monday   @ 04:09 EST, run expanded tests against v1.10.x
  workflow_dispatch:

env:
  VERSION: '1.0.0-ci'
  GLOO_LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  fed_tests_dev:
    name: fed regression tests (fed@k8s${{matrix.kube-version.kubectl}})
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 5 * * 1-5'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [{ node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' }]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fed-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}
  canary_tests_dev:
    name: fed regression tests (fed-canary@k8s${{matrix.kube-version.kubectl}})
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 5 * * 1-5'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [{ node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' }]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/canary-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  fed_tests_13:
    name: fed regression tests (fed@k8s${{matrix.kube-version.kubectl}})
    if: github.event.schedule == '6 6 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.13.x
      - uses: ./.github/actions/fed-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}
  canary_tests_13:
    name: fed regression tests (fed-canary@k8s${{matrix.kube-version.kubectl}})
    if: github.event.schedule == '6 6 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.13.x
      - uses: ./.github/actions/canary-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  fed_tests_12:
    name: fed regression tests (fed@k8s${{matrix.kube-version.kubectl}})
    if: github.event.schedule == '7 7 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.12.x
      - uses: ./.github/actions/fed-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}
  canary_tests_12:
    name: fed regression tests (fed-canary@k8s${{matrix.kube-version.kubectl}})
    if: github.event.schedule == '7 7 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.12.x
      - uses: ./.github/actions/canary-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  fed_tests_11:
    name: fed regression tests (fed@k8s${{matrix.kube-version.kubectl}})
    if: github.event.schedule == '8 8 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.11.x
      - uses: ./.github/actions/fed-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  fed_tests_10:
    name: fed regression tests (fed@k8s${{matrix.kube-version.kubectl}})
    if: github.event.schedule == '9 9 * * 1'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        kube-version: [ { node: 'v1.21.14', kubectl: 'v1.21.14', kind: 'v0.17.0' },
                        { node: 'v1.24.7@sha256:5c015142d9b60a0f6c45573f809957076514e38ec973565e2b2fe828b91597f5', kubectl: 'v1.24.7', kind: 'v0.17.0' } ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.10.x
      - uses: ./.github/actions/fed-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  publish_results:
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    needs: [ fed_tests_dev, canary_tests_dev, fed_tests_13, canary_tests_13, fed_tests_12, canary_tests_12, fed_tests_11, fed_tests_10 ]
    steps:
      - uses: actions/checkout@v3
      - name: compute-preamble
        id: compute-preamble
        shell: bash
        run: |
          echo "SLACK_CHANNEL=C04CJMXAH7A" >> $GITHUB_ENV     #edge-nightly-results by default
          if [[ ${{github.event_name == 'workflow_dispatch'}} = true ]]; then
            preamble="Gloo Fed nightlies (manual run)"
            echo "SLACK_CHANNEL=C0314KESVNV" >> $GITHUB_ENV   #slack-integration-testing if manually run
          elif [[ ${{github.event.schedule == '9 9 * * 1'}} = true ]]; then
              preamble="Gloo Fed weeklies (v1.10.x)"
          elif [[ ${{github.event.schedule == '8 8 * * 1'}} = true ]]; then
              preamble="Gloo Fed weeklies (v1.11.x)"
          elif [[ ${{github.event.schedule == '7 7 * * 1'}} = true ]]; then
              preamble="Gloo Fed weeklies (v1.12.x)"
          elif [[ ${{github.event.schedule == '6 6 * * 1'}} = true ]]; then
              preamble="Gloo Fed weeklies (v1.13.x)"
          elif [[ ${{github.event.schedule == '0 5 * * 1-5'}} = true ]]; then
              preamble="Gloo Fed nightlies (dev)"
          fi
          echo "Setting PREAMBLE as $preamble"
          echo "::set-output name=preamble::$(echo $preamble)"
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.2
      - uses: actions/download-artifact@v3
      - name: send slack message
        env:
          PARENT_JOB_URL: https://github.com/solo-io/solo-projects/actions/runs/${{github.run_id}} # parent job hyperlink
          PREAMBLE: ${{ steps.compute-preamble.outputs.preamble }}  # text to hyperlink at start of slack message
          SLACKBOT_BEARER: ${{ secrets.SLACKBOT_BEARER }}
        run: |
          test_results="$(cat */test-out.json | jq -c --slurp .)"
          echo $test_results
          go run .github/workflows/helpers/notify/notify-from-json.go $test_results