name: Enterprise Nightly Tests
run-name: EE Nightly ${{github.event.schedule}} by @${{ github.actor }}

env:
  VERSION: '1.0.0-ci'
  GLOO_LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
  GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
  QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
  TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

on:
  # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
  # Minute [0,59]
  # Hour [0,23]
  # Day of the month [1,31]
  # Month of the year [1,12]
  # Day of the week ([0,6] with 0=Sunday)
  schedule:
    - cron: "0 5 * * 1-5" # weekdays @ 05:00 UTC, run tests against latest main
    - cron: "0 6 * * 1"   # monday   @ 06:00 UTC, run expanded tests against v1.15.x
    - cron: "0 7 * * 1"   # monday   @ 07:00 UTC, run expanded tests against v1.14.x
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to run tests against"
        type: choice
        options:
          - main
          - v1.15.x
          - v1.14.x
      run-regression:
        description: "Run regression tests"
        type: boolean
      run-performance:
        description: "Run performance tests"
        type: boolean

jobs:
  regression_tests_main:
    name: main regression tests (${{matrix.kube-e2e-test-type.test}}@k8s${{matrix.kube-version.kubectl}})
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run-regression && inputs.branch == 'main') || github.event.schedule == '0 5 * * 1-5' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: [{test: 'gateway', use-fips: 'true'}, {test: 'gateway', use-fips: 'false'}, { test: "gloo-mtls", use-fips: 'true' }, {test: 'gloo-mtls', use-fips: 'false'}, {test: 'helm', use-fips: 'false'}, {test: 'redis-clientside-sharding', use-fips: 'false'}, {test: 'wasm', use-fips: 'false'}, {test: 'caching', use-fips: 'false'}, {test: 'upgrade', use-fips: 'false'}, {test: 'argocd', use-fips: 'false'}]
        kube-version: [ { node: 'v1.24.15@sha256:7db4f8bea3e14b82d12e044e25e34bd53754b7f2b0e9d56df21774e6f66a70ab', kubectl: 'v1.24.17', kind: 'v0.20.0', helm: 'v3.12.2', argocd: 'v2.8.4' },
                        { node: 'v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31', kubectl: 'v1.28.4', kind: 'v0.20.0', helm: 'v3.13.2', argocd: 'v2.8.4' }]
        exclude:
          # Disabling wasm tests since pulling from host webassemblyhub.io consistently fails
          - kube-e2e-test-type: {test: 'wasm', use-fips: 'false'}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/workflows/composite-actions/regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ env.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ env.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ env.TESTSPACE_TOKEN }}

  regression_tests_15:
    name: v1.15.x regression tests (${{matrix.kube-e2e-test-type.test}}@k8s${{matrix.kube-version.kubectl}})
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run-regression && inputs.branch == 'v1.15.x') || github.event.schedule == '0 6 * * 1' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: [{test: 'gateway', use-fips: 'true'}, {test: 'gateway', use-fips: 'false'}, {test: 'gloo-mtls', use-fips: 'false'}, {test: 'helm', use-fips: 'false'}, {test: 'redis-clientside-sharding', use-fips: 'false'}, {test: 'wasm', use-fips: 'false'}, {test: 'caching', use-fips: 'false'}, {test: 'upgrade', use-fips: 'false'}]
        kube-version: [ { node: 'v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61', kubectl: 'v1.23.17', kind: 'v0.17.0', helm: 'v3.11.2' },
                        { node: 'v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72', kubectl: 'v1.27.3', kind: 'v0.20.0', helm: 'v3.12.2' }]
        exclude:
          # Disabling wasm tests since pulling from host webassemblyhub.io consistently fails
          - kube-e2e-test-type: {test: 'wasm', use-fips: 'false'}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.15.x
      - uses: ./.github/workflows/composite-actions/regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ env.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ env.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ env.TESTSPACE_TOKEN }}

  regression_tests_14:
    name: v1.14.x regression tests (${{matrix.kube-e2e-test-type.test}}@k8s${{matrix.kube-version.kubectl}})
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run-regression && inputs.branch == 'v1.14.x') || github.event.schedule == '0 7 * * 1' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        kube-e2e-test-type: [{test: 'gateway', use-fips: 'true'}, {test: 'gateway', use-fips: 'false'}, {test: 'gloo-mtls', use-fips: 'false'}, {test: 'helm', use-fips: 'false'}, {test: 'redis-clientside-sharding', use-fips: 'false'}, {test: 'wasm', use-fips: 'false'}, {test: 'caching', use-fips: 'false'}, {test: 'upgrade', use-fips: 'false'}, {test: 'argocd', use-fips: 'false'}]
        kube-version: [ { node: 'v1.21.14@sha256:9d9eb5fb26b4fbc0c6d95fa8c790414f9750dd583f5d7cee45d92e8c26670aa1', kubectl: 'v1.21.14', kind: 'v0.17.0', helm: 'v3.9.4', argocd: 'v2.8.4' },
        { node: 'v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315', kubectl: 'v1.24.7', kind: 'v0.17.0', helm: 'v3.9.4', argocd: 'v2.8.4' } ]
        exclude:
          # Disabling wasm tests since pulling from host webassemblyhub.io consistently fails
          - kube-e2e-test-type: {test: 'wasm', use-fips: 'false'}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.14.x
      - uses: ./.github/workflows/composite-actions/regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ env.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ env.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ env.TESTSPACE_TOKEN }}

  performance_tests_main:
    name: main performance tests
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run-performance && inputs.branch == 'main') || github.event.schedule == '0 5 * * 1-5' }}
    runs-on: ubuntu-20.04-8core
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/workflows/composite-actions/standard-gloo-ee-setup
        with:
          GLOO_EE_GCR_KEY: ${{ env.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ env.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      - uses: ./.github/workflows/composite-actions/performance-tests

  performance_tests_15:
    name: v1.15.x performance tests
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run-performance && inputs.branch == 'v1.15.x') || github.event.schedule == '0 6 * * 1' }}
    runs-on: ubuntu-20.04-8core
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v1.15.x
      - uses: ./.github/workflows/composite-actions/standard-gloo-ee-setup
        with:
          GLOO_EE_GCR_KEY: ${{ env.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ env.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      - uses: ./.github/workflows/composite-actions/performance-tests

  performance_tests_14:
    # There are no performance tests for v1.14.x.
    # As a result, we don't use an 8core runner and don't include a schedule trigger
    name: v1.14.x performance tests
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run-performance && inputs.branch == 'v1.14.x'}}
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - run: echo "v1.14.x performance tests do not exist"
        shell: bash

  publish_results:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: ${{ always() }}
    needs:
      - regression_tests_main
      - regression_tests_15
      - regression_tests_14
      - performance_tests_main
      - performance_tests_15
      - performance_tests_14
    steps:
      - uses: actions/checkout@v3
      - name: compute-preamble
        id: compute-preamble
        shell: bash
        run: |
          echo "SLACK_CHANNEL=C04CJMXAH7A" >> $GITHUB_ENV     #edge-nightly-results by default
          if [[ ${{github.event_name == 'workflow_dispatch'}} = true ]]; then
            trigger="Gloo EE Manual run"
            branch=${{ inputs.branch }}
            echo "SLACK_CHANNEL=C0314KESVNV" >> $GITHUB_ENV   #slack-integration-testing if manually run
          elif [[ ${{github.event.schedule == '0 7 * * 1'}} = true ]]; then
            trigger="Gloo EE weeklies"
            branch="v1.14.x"
          elif [[ ${{github.event.schedule == '0 6 * * 1'}} = true ]]; then
            trigger="Gloo EE weeklies"
            branch="v1.15.x"
          elif [[ ${{github.event.schedule == '0 5 * * 1-5'}} = true ]]; then
            trigger="Gloo EE nightlies"
            branch="main"
          fi

          preamble="$trigger ($branch)"
          echo "Setting PREAMBLE as $preamble"
          echo "preamble=$(echo $preamble)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v4
        with:
          # Caching in setup-go is on by default
          # In our prep-go-runner we use a more configurable cache https://github.com/actions/cache
          # In this step, we don't need to store a new cache entry because it runs infrequently and
          # will pollute the cache entries
          cache: false
          go-version-file: go.mod
      - uses: actions/download-artifact@v3
      - name: send slack message
        env:
          PARENT_JOB_URL: https://github.com/solo-io/solo-projects/actions/runs/${{github.run_id}} # parent job hyperlink
          PREAMBLE: ${{ steps.compute-preamble.outputs.preamble }}  # text to hyperlink at start of slack message
          SLACKBOT_BEARER: ${{ secrets.SLACKBOT_BEARER }}
        run: |
          test_results="$(cat */test-out.json | jq -c --slurp .)"
          echo $test_results
          go run .github/workflows/helpers/notify/notify-from-json.go $test_results