name: GGII Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test_gloo_gateway2:
    name: Build and Test Gloo Gateway 2
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Build
      run: go build -v ./projects/gateway2/... ./projects/gloo/cli/cmd
    - name: Install utils for env tests
      run: make -C ./projects/gateway2/ install-go-tools
    - name: Test with the Go CLI
      run: go test ./projects/gateway2/...

  conformance:
    name: Run Gateway api conformance tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Install kind
      uses: helm/kind-action@v1.5.0
      with:
        install_only: true
        version: v0.20.0
    - name: Set up cluster and helm chart
      run: ./ci/kind/setup-kind.sh
    - name: Additional cluster setup
      run: ./projects/gateway2/kind.sh
    - name: Install Gloo Gateway
      run: helm upgrade -i -n gloo-system gloo ./_test/gloo-1.0.0-ci.tgz --create-namespace -f ./projects/gateway2/tests/conformance/test-values.yaml
    - name: Pre-test cleanup of resources
      run: kubectl delete rs --all
    - name: Test Conformance
      run: make -C ./projects/gateway2/ conformance

  snapshot_tests:
    name: Snapshot e2e Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        # Runs same tests with the k8s gateway api and classic edge apis
        api-type: [ 'gateway', 'classic' ]
        kube-version: [ { node: 'v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31', kubectl: 'v1.28.4', kind: 'v0.20.0', helm: 'v3.13.2' } ]
        merge-to-main:
          - ${{ github.event.pull_request.base.ref == 'main' }}
        exclude:
          - merge-to-main: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Prep Go Runner
        uses: ./.github/workflows/composite-actions/prep-go-runner
      - name: Install kind
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true
          version: ${{ matrix.kube-version.kind }}
      - uses: azure/setup-kubectl@v3
        id: kubectl
        with:
          version: ${{ matrix.kube-version.kubectl }}
      - uses: azure/setup-helm@v3
        with:
          version: ${{ matrix.kube-version.helm }}
      - name: Setup env and run snapshot tests
        shell: bash
        env:
          CLUSTER_NAME: 'kind'
          CLUSTER_NODE_VERSION: ${{ matrix.kube-version.node }}
        run: |
          export KUBERNETES_MASTER=$HOME/.kube
          export ISTIOCTL_VERSION=1.18.2
          export ISTIO_HUB=docker.io/istio
          export VERSION=1.0.1-dev
          export ISTIO_VERSION=1.18.2
          make run-${{ api-type }}-snapshot-e2e-tests