name: CI

on: pull_request

env:
  VERSION: '1.0.0-ci'
  GLOO_LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  gloo_fed_e2e_tests:
    # when a job runs with a matrix, its name changes automatically.  HOWEVER, it can be dynamically computed
    # based on matrix variables.  Doing this (below) lets us satisfy the admin requirement of a test called
    # "Gloo Fed E2E Tests" to run during a PR's CI
    name: ${{matrix.name-helper}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        name-helper: ['Gloo Fed E2E Tests']
        kube-version: [{ node: 'v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f', kubectl: 'v1.26.4', kind: 'v0.18.0', helm: 'v3.11.2' }]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fed-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  gloo_fed_canary_tests:
    # when a job runs with a matrix, its name changes automatically.  HOWEVER, it can be dynamically computed
    # based on matrix variables.  Doing this (below) lets us satisfy the admin requirement of a test called
    # "Gloo Fed Canary Tests" to run during a PR's CI
    name: ${{matrix.name-helper}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        name-helper: ['Gloo Fed Canary Tests']
        kube-version: [{ node: 'v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f', kubectl: 'v1.26.4', kind: 'v0.18.0', helm: 'v3.11.2' }]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/canary-regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}

  regression_tests:
    name: k8s regression tests (${{matrix.kube-e2e-test-type.test}}, ${{matrix.kube-e2e-test-type.use-fips}})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # update tests are not run on PRs
        kube-e2e-test-type: [{test: 'gateway', use-fips: 'true'}, {test: 'gateway', use-fips: 'false'}, {test: 'gloo-mtls', use-fips: 'false'}, {test: 'helm', use-fips: 'false'}, {test: 'redis-clientside-sharding', use-fips: 'false'}, {test: 'wasm', use-fips: 'false'}, {test: 'caching', use-fips: 'false'}, {test: 'upgrade', use-fips: 'false'}]
        kube-version: [{ node: 'v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f', kubectl: 'v1.26.4', kind: 'v0.18.0', helm: 'v3.11.2' }]
        merge-to-main:
          - ${{ github.event.pull_request.base.ref == 'main' }}
        exclude:
          - merge-to-main: true
            kube-e2e-test-type: {test: 'upgrade', use-fips: 'false'}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/regression-tests
        with:
          GLOO_EE_GCR_KEY: ${{ secrets.GLOO_EE_GCR_KEY }}
          QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.CI_ADMIN_GITHUB_TOKEN }}
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}
